export const data = [
  {
    view: "View",
    emailStatus: "Sent",
    book: "The Baji Mantis",
    author: "A. Joshua Chiatovich",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 18.22",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 18.22",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Star Signs: Primordial",
    author: "Aaron Chandler",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 1.93",
    broughtforwardAmount: "£ 8.15",
    totalAmount: "£ 10.08",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Mail Le Land - E-Book",
    author: "Abayomi Ogunsola",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 0.00",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 0.00",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Sent",
    book: "The Baji Mantis",
    author: "A. Joshua Chiatovich",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 18.22",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 18.22",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Star Signs: Primordial",
    author: "Aaron Chandler",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 1.93",
    broughtforwardAmount: "£ 8.15",
    totalAmount: "£ 10.08",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Mail Le Land - E-Book",
    author: "Abayomi Ogunsola",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 0.00",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 0.00",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Sent",
    book: "The Baji Mantis",
    author: "A. Joshua Chiatovich",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 18.22",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 18.22",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Star Signs: Primordial",
    author: "Aaron Chandler",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 1.93",
    broughtforwardAmount: "£ 8.15",
    totalAmount: "£ 10.08",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Mail Le Land - E-Book",
    author: "Abayomi Ogunsola",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 0.00",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 0.00",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Sent",
    book: "The Baji Mantis",
    author: "A. Joshua Chiatovich",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 18.22",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 18.22",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Star Signs: Primordial",
    author: "Aaron Chandler",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 1.93",
    broughtforwardAmount: "£ 8.15",
    totalAmount: "£ 10.08",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Mail Le Land - E-Book",
    author: "Abayomi Ogunsola",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 0.00",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 0.00",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Sent",
    book: "The Baji Mantis",
    author: "A. Joshua Chiatovich",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 18.22",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 18.22",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Star Signs: Primordial",
    author: "Aaron Chandler",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 1.93",
    broughtforwardAmount: "£ 8.15",
    totalAmount: "£ 10.08",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Mail Le Land - E-Book",
    author: "Abayomi Ogunsola",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 0.00",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 0.00",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Sent",
    book: "The Baji Mantis",
    author: "A. Joshua Chiatovich",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 18.22",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 18.22",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Star Signs: Primordial",
    author: "Aaron Chandler",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 1.93",
    broughtforwardAmount: "£ 8.15",
    totalAmount: "£ 10.08",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Mail Le Land - E-Book",
    author: "Abayomi Ogunsola",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 0.00",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 0.00",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Sent",
    book: "The Baji Mantis",
    author: "A. Joshua Chiatovich",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 18.22",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 18.22",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Star Signs: Primordial",
    author: "Aaron Chandler",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 1.93",
    broughtforwardAmount: "£ 8.15",
    totalAmount: "£ 10.08",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Mail Le Land - E-Book",
    author: "Abayomi Ogunsola",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 0.00",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 0.00",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Sent",
    book: "The Baji Mantis",
    author: "A. Joshua Chiatovich",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 18.22",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 18.22",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Star Signs: Primordial",
    author: "Aaron Chandler",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 1.93",
    broughtforwardAmount: "£ 8.15",
    totalAmount: "£ 10.08",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Mail Le Land - E-Book",
    author: "Abayomi Ogunsola",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 0.00",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 0.00",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Sent",
    book: "The Baji Mantis",
    author: "A. Joshua Chiatovich",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 18.22",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 18.22",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Star Signs: Primordial",
    author: "Aaron Chandler",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 1.93",
    broughtforwardAmount: "£ 8.15",
    totalAmount: "£ 10.08",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Mail Le Land - E-Book",
    author: "Abayomi Ogunsola",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 0.00",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 0.00",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Sent",
    book: "The Baji Mantis",
    author: "A. Joshua Chiatovich",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 18.22",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 18.22",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Star Signs: Primordial",
    author: "Aaron Chandler",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 1.93",
    broughtforwardAmount: "£ 8.15",
    totalAmount: "£ 10.08",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
  {
    view: "View",
    emailStatus: "Not Sent",
    book: "Mail Le Land - E-Book",
    author: "Abayomi Ogunsola",
    duration: "2024-1",
    issueDate: "11-07-2024",
    royaltiesAmount: "£ 0.00",
    broughtforwardAmount: "£ 0.00",
    totalAmount: "£ 0.00",
    status: "Issued",
    paymentDate: "0000-00-00",
    delete: "Delete",
  },
];
