export const booksData = [
    {
        status: "Under Production",
        penName: "Dr Clifford Mushishi",
        bookTitle: "The United Methodist Church - A Handbook",
        imprint: "Olympia Publishers",
        images: "No images available",
        contractDate: "08-07-2013",
        authorForms: { form1: true, form2: false, form3: true },
        HS: "Not specified",
        coverBlurb: "A comprehensive handbook...",
        proofsFormat: "PDF",
        remainingDays: "0",
        daysActivated: { date: "10-10-2022", completed: true },
        coverDesign: { date: "10-10-2022", completed: true },
        firstProofsReader: { date: "21-04-2022", completed: true },
        firstProofsAuthor: { date: "06-05-2022", completed: true },
        firstProofsAmender: { date: "09-10-2023", completed: true },
        secondProofsAuthor: { date: "13-11-2023", completed: true },
        thirdProofsAuthor: { date: "24-01-2024", completed: true },
        coverCertificateReceived: { date: "10-10-2022", completed: true },
        proofsCertificateReceived: "Pending",
        finalisedForPrint: "No",
        sendForFinalCheck: "Send",
        publicationDate: "",
        contractPaymentStatus: "Paying",
        notes: "",
    },
    {
        status: "Under Production",
        penName: "Steve Crawford",
        bookTitle: "Poet for The Lord -- The Word in Verse",
        imprint: "Olympia Publishers",
        images: "No images available",
        contractDate: "26-03-2020",
        remainingDays: "0",
        daysActivated: "20-05-2021",
        authorForms: { form1: true, form2: false, form3: true },
        HS: "Not specified",
        coverBlurb: "A collection of spiritual verses...",
        proofsFormat: "PDF",
        coverDesign: { date: "11-10-2022", completed: true },
        firstProofsReader: { date: "15-07-2020", completed: true },
        firstProofsAuthor: { date: "07-08-2020", completed: true },
        firstProofsAmender: { date: "09-09-2020", completed: true },
        secondProofsAuthor: { date: "14-09-2020", completed: true },
        thirdProofsAuthor: { date: "19-04-2021", completed: true },
        coverCertificateReceived: { date: "11-10-2022", completed: true },
        proofsCertificateReceived: "Pending",
        finalisedForPrint: "No",
        sendForFinalCheck: "Send",
        publicationDate: "",
        contractPaymentStatus: "Paid in full",
        notes: "",
    },
    {
        status: "Under Production",
        penName: "Jacqueline Bell CBT",
        bookTitle: "Breaking Barriers in Anxiety, Depression & Stress",
        imprint: "Olympia Publishers",
        images: "No images available",
        contractDate: "21-09-2020",
        remainingDays: "0",
        daysActivated: "10-11-2021",
        authorForms: { form1: true, form2: false, form3: true },
        HS: "Not specified",
        coverBlurb: "A guide to overcoming mental health challenges...",
        proofsFormat: "PDF",
        coverDesign: { date: "11-10-2022", completed: true },
        firstProofsReader: { date: "29-01-2021", completed: true },
        firstProofsAuthor: { date: "15-02-2021", completed: true },
        firstProofsAmender: { date: "01-04-2021", completed: true },
        secondProofsAuthor: { date: "12-04-2021", completed: true },
        thirdProofsAuthor: { date: "05-07-2021", completed: true },
        coverCertificateReceived: { date: "11-10-2022", completed: true },
        proofsCertificateReceived: "Pending",
        finalisedForPrint: "No",
        sendForFinalCheck: "Send",
        publicationDate: "",
        contractPaymentStatus: "Paid in full",
        notes: "",
    }
];
