export const data = [
  {
    firstName: "Sophie",
    lastName: "Cloud",
    company: "Acme Corp",
    vat: "",
    telephone: "",
    mobile: "",
    emails: "sophie.cloud@acme.com",
    skype: "",
    website: "www.acme.com",
    address1: "625 Kings Road London SW6 2ES",
    address2: "Fulham London SW6 2ES",
    signupDate: "2024-05-24",
  },
  {
    firstName: "Keith",
    lastName: "Sharp",
    company: "Sharp Inc",
    vat: "",
    telephone: "07768336991",
    mobile: "",
    emails: "sharpkeith@aol.com",
    skype: "",
    website: "",
    address1: "88 Corbyn Street, London London United Kingdom N4 3BZ",
    address2: "London London United Kingdom N4 3BZ",
    signupDate: "2024-03-28",
  },
  {
    firstName: "Sophie",
    lastName: "Peacock",
    company: "Peacock Ltd",
    vat: "",
    telephone: "",
    mobile: "",
    emails: "",
    skype: "",
    website: "",
    address1: "36 Wisbech Road Ely Cambridgeshire",
    address2: "Littleport Ely Cambridgeshire",
    signupDate: "2024-01-04",
  },
  {
    firstName: "Alisha",
    lastName: "McMillen",
    company: "McMillen Associates",
    vat: "",
    telephone: "",
    mobile: "",
    emails: "",
    skype: "",
    website: "",
    address1: "",
    address2: "",
    signupDate: "2023-08-11",
  },
  {
    firstName: "Rachael",
    lastName: "Munro",
    company: "Munro Partners",
    vat: "",
    telephone: "",
    mobile: "",
    emails: "",
    skype: "",
    website: "",
    address1: "",
    address2: "",
    signupDate: "2023-08-03",
  },
  {
    firstName: "Christy",
    lastName: "Johns",
    company: "Johns Enterprise",
    vat: "",
    telephone: "",
    mobile: "",
    emails: "",
    skype: "",
    website: "",
    address1: "",
    address2: "",
    signupDate: "2023-08-03",
  },
  {
    firstName: "Brian",
    lastName: "Johnson",
    company: "Johnson Holdings",
    vat: "",
    telephone: "07557407450",
    mobile: "",
    emails: "beachhampton@gmail.com",
    skype: "",
    website: "",
    address1: "Flat 2, 1 Castle Row London Surrey United Kingdom W4 4JQ",
    address2: "Horticultural Place London Surrey United Kingdom W4 4JQ",
    signupDate: "2023-02-16",
  },
  {
    firstName: "Mike",
    lastName: "Purewal",
    company: "Purewal Technologies",
    vat: "",
    telephone: "1-647-284-8211",
    mobile: "",
    emails: "mike.r.purewal@gmail.com",
    skype: "",
    website: "",
    address1: "94 Stephensbrook Circle Stouffville Ontario Canada L4A 0G5",
    address2: "Stouffville Ontario Canada L4A 0G5",
    signupDate: "2023-02-08",
  },
  {
    firstName: "Georgia",
    lastName: "Chadburn-Jones",
    company: "Chadburn-Jones LLC",
    vat: "",
    telephone: "",
    mobile: "",
    emails: "",
    skype: "",
    website: "",
    address1: "3 Eastbourne Crescent Stockport Cheshire United Kingdom SK5 8BJ",
    address2: "Stockport Cheshire United Kingdom SK5 8BJ",
    signupDate: "2023-01-26",
  },
];

export const invoices = [
  {
    InvoiceNo: "C101",
    Product1: "Repayment of Directors Drawings",
    Product2: "",
    Product3: "",
    Amount1: 20000,
    Amount2: 0,
    Amount3: 0,
    DueDate: null,
    Net: 20000,
    Vat: 0,
    Total: 20000.0,
    PaymentDetail: "paid by BACS",
  },
  {
    InvoiceNo: "C101",
    Product1: "Repayment of Directors Drawings",
    Product2: "",
    Product3: "",
    Amount1: 20000,
    Amount2: 0,
    Amount3: 0,
    DueDate: null,
    Net: 20000,
    Vat: 0,
    Total: 20000.0,
    PaymentDetail: "paid by BACS",
  },
  {
    InvoiceNo: "C101",
    Product1: "Repayment of Directors Drawings",
    Product2: "",
    Product3: "",
    Amount1: 20000,
    Amount2: 0,
    Amount3: 0,
    DueDate: null,
    Net: 20000,
    Vat: 0,
    Total: 20000.0,
    PaymentDetail: "paid by BACS",
  },
  {
    InvoiceNo: "C101",
    Product1: "Repayment of Directors Drawings",
    Product2: "",
    Product3: "",
    Amount1: 20000,
    Amount2: 0,
    Amount3: 0,
    DueDate: null,
    Net: 20000,
    Vat: 0,
    Total: 20000.0,
    PaymentDetail: "paid by BACS",
  },
  {
    InvoiceNo: "C101",
    Product1: "Repayment of Directors Drawings",
    Product2: "",
    Product3: "",
    Amount1: 20000,
    Amount2: 0,
    Amount3: 0,
    DueDate: null,
    Net: 20000,
    Vat: 0,
    Total: 20000.0,
    PaymentDetail: "paid by BACS",
  },
  {
    InvoiceNo: "C101",
    Product1: "Repayment of Directors Drawings",
    Product2: "",
    Product3: "",
    Amount1: 20000,
    Amount2: 0,
    Amount3: 0,
    DueDate: null,
    Net: 20000,
    Vat: 0,
    Total: 20000.0,
    PaymentDetail: "paid by BACS",
  },
  {
    InvoiceNo: "C101",
    Product1: "Repayment of Directors Drawings",
    Product2: "",
    Product3: "",
    Amount1: 20000,
    Amount2: 0,
    Amount3: 0,
    DueDate: null,
    Net: 20000,
    Vat: 0,
    Total: 20000.0,
    PaymentDetail: "paid by BACS",
  },
  {
    InvoiceNo: "C101",
    Product1: "Repayment of Directors Drawings",
    Product2: "",
    Product3: "",
    Amount1: 20000,
    Amount2: 0,
    Amount3: 0,
    DueDate: null,
    Net: 20000,
    Vat: 0,
    Total: 20000.0,
    PaymentDetail: "paid by BACS",
  },
  {
    InvoiceNo: "C101",
    Product1: "Repayment of Directors Drawings",
    Product2: "",
    Product3: "",
    Amount1: 20000,
    Amount2: 0,
    Amount3: 0,
    DueDate: null,
    Net: 20000,
    Vat: 0,
    Total: 20000.0,
    PaymentDetail: "paid by BACS",
  },
  {
    InvoiceNo: "C101",
    Product1: "Repayment of Directors Drawings",
    Product2: "",
    Product3: "",
    Amount1: 20000,
    Amount2: 0,
    Amount3: 0,
    DueDate: null,
    Net: 20000,
    Vat: 0,
    Total: 20000.0,
    PaymentDetail: "paid by BACS",
  },
];
