export const data = [
  {
    invoiceType: "Contract Invoice",
    date: "14-05-2121",
    invoiceNumber: "no number",
    contactName: "Rebecca Clark",
    cardType: "Visa Debit",
    totalAmount: "£190",
    billingName: "",
    completedBy: "Courtney",
    status: "Processing",
  },
  {
    invoiceType: "Contract Invoice",
    date: "19-04-2121",
    invoiceNumber: "no number",
    contactName: "Jennifer Motley",
    cardType: "Visa Debit",
    totalAmount: "£25",
    billingName: "",
    completedBy: "Courtney",
    status: "Processing",
  },
  {
    invoiceType: "Contract Invoice",
    date: "14-05-2121",
    invoiceNumber: "no number",
    contactName: "Rebecca Clark",
    cardType: "Visa Debit",
    totalAmount: "£190",
    billingName: "",
    completedBy: "Courtney",
    status: "Processing",
  },
  {
    invoiceType: "Contract Invoice",
    date: "19-04-2121",
    invoiceNumber: "no number",
    contactName: "Jennifer Motley",
    cardType: "Visa Debit",
    totalAmount: "£25",
    billingName: "",
    completedBy: "Courtney",
    status: "Processing",
  },
  {
    invoiceType: "Contract Invoice",
    date: "14-05-2121",
    invoiceNumber: "no number",
    contactName: "Rebecca Clark",
    cardType: "Visa Debit",
    totalAmount: "£190",
    billingName: "",
    completedBy: "Courtney",
    status: "Processing",
  },
  {
    invoiceType: "Contract Invoice",
    date: "19-04-2121",
    invoiceNumber: "no number",
    contactName: "Jennifer Motley",
    cardType: "Visa Debit",
    totalAmount: "£25",
    billingName: "",
    completedBy: "Courtney",
    status: "Processing",
  },
  {
    invoiceType: "Contract Invoice",
    date: "14-05-2121",
    invoiceNumber: "no number",
    contactName: "Rebecca Clark",
    cardType: "Visa Debit",
    totalAmount: "£190",
    billingName: "",
    completedBy: "Courtney",
    status: "Processing",
  },
  {
    invoiceType: "Contract Invoice",
    date: "19-04-2121",
    invoiceNumber: "no number",
    contactName: "Jennifer Motley",
    cardType: "Visa Debit",
    totalAmount: "£25",
    billingName: "",
    completedBy: "Courtney",
    status: "Processing",
  },
  {
    invoiceType: "Contract Invoice",
    date: "14-05-2121",
    invoiceNumber: "no number",
    contactName: "Rebecca Clark",
    cardType: "Visa Debit",
    totalAmount: "£190",
    billingName: "",
    completedBy: "Courtney",
    status: "Processing",
  },
  {
    invoiceType: "Contract Invoice",
    date: "19-04-2121",
    invoiceNumber: "no number",
    contactName: "Jennifer Motley",
    cardType: "Visa Debit",
    totalAmount: "£25",
    billingName: "",
    completedBy: "Courtney",
    status: "Processing",
  }, {
    invoiceType: "Contract Invoice",
    date: "14-05-2121",
    invoiceNumber: "no number",
    contactName: "Rebecca Clark",
    cardType: "Visa Debit",
    totalAmount: "£190",
    billingName: "",
    completedBy: "Courtney",
    status: "Processing",
  },
  {
    invoiceType: "Contract Invoice",
    date: "19-04-2121",
    invoiceNumber: "no number",
    contactName: "Jennifer Motley",
    cardType: "Visa Debit",
    totalAmount: "£25",
    billingName: "",
    completedBy: "Courtney",
    status: "Processing",
  },
];

export const paymentData = [
  {
    Date: "14-05-2121",
    "Invoice Type": "Contract Invoice",
    "Invoice number / Ref": "no number",
    "Contact name": "Rebecca Clark",
    "Card type": "Visa Debit",
    "Card Number": "4462593563111324",
    "Card Expiry date (mmyy)": "0721",
    "CV2 (security code at back)": "872",
    "Name on the card": "R Clarke",
    "Total amount": "£190",
    Notes: "",
    "First name": "",
    "Last name": "",
    "Phone number": "",
    "Email address": "bettyccboop@gmail.com",
    "Address line 1": "",
    "Address line 2": "",
    Town: "",
    City: "",
    "Post code": "N19 3ta",
    Country: "United Kingdom",
    "Completed by": "Courtney",
    Status: "Processing",
  },
];

