export const data = [
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: false, form2: false, form3: true },
    paymentStatus: "Traditional",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: false, form2: true, form3: false },
    paymentStatus: "Paying",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Paid in Full",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Hardback",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: false, form2: false, form3: true },
    paymentStatus: "Traditional",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: false, form2: true, form3: false },
    paymentStatus: "Paying",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Paid in Full",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Hardback",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: false, form2: false, form3: true },
    paymentStatus: "Traditional",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: false, form2: true, form3: false },
    paymentStatus: "Paying",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Paid in Full",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Hardback",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: false, form2: false, form3: true },
    paymentStatus: "Traditional",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: false, form2: true, form3: false },
    paymentStatus: "Paying",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Paid in Full",
  },
  {
    status: "Under Production",
    imprint: "Olympia Publishers",
    author: "Edgardo Samaniego",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    isbn: "978-1-83543-485-7",
    dateContract: "01-07-2024",
    datePublication: "-",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Hardback",
  },
];
