export const menuItems = [
  { to: "/", label: "Home" },
  { to: "/contract", label: "Contract" },
  { to: "/author", label: "Author" },
  { to: "/book", label: "Book" },
  { to: "/editorial", label: "Editorial" },
  { to: "/publicity", label: "Publicity" },
  { to: "/book-invoices", label: "Book Invoices" },
  { to: "/purchases", label: "Purchases" },
  { to: "/delivery-notes", label: "Delivery Notes" },
  { to: "/book-orders", label: "Book Orders" },
  { to: "/bumblebee", label: "Bumblebee" },
  { to: "/production", label: "Production" },
  { to: "/final-check", label: "Final Check" },
  {
    to: "/others",
    label: "Others",
    submenuItems: [
      { to: "/royalties", label: "Royalties" },
      { to: "/graphics", label: "Graphics" },
      { to: "/card-payments", label: "Card Payments" },
      { to: "/bookshops", label: "Bookshops" },
      { to: "/printers", label: "Printers" },
      { to: "/other-clients", label: "Other Clients" },
      { to: "/archive", label: "Archive" },
      { to: "/outworkers", label: "Outworkers" },
      { to: "/posts", label: "Posts" },
      { to: "/reports", label: "Reports" },
      { to: "/ready-for-publication", label: "Ready for Publications" },
      { to: "/published-books", label: "Published Books" },
      {
        to: "/olympia-websites-portal",
        label: "Olympia Websites Control Panel",
      },
    ],
  },
];
