export const menuItems = [
  { to: "/", label: "Home" },
  { to: "/contract", label: "Contract" },
  { to: "/author", label: "Author" },
  { to: "/book", label: "Book" },
  { to: "/editorial", label: "Editorial" },
  { to: "/publicity", label: "Publicity" },
  { to: "/invoices", label: "Book Invoices" },
  { to: "/purchases", label: "Purchases" },
  { to: "/delivery-notes", label: "Delivery Notes" },
  { to: "/orders", label: "Book Orders" },
  { to: "/bumblebee", label: "Bumblebee" },
  { to: "/production", label: "Production" },
  { to: "/final-check", label: "Final Check" },
  {
    to: "/others",
    label: "Others",
    submenuItems: [
      { to: "#", label: "Royalties" },
      { to: "#", label: "Graphics" },
      { to: "#", label: "Card Payments" },
      { to: "#", label: "Bookshops" },
      { to: "#", label: "Printers" },
      { to: "#", label: "Other Clients" },
      { to: "#", label: "Archive" },
      { to: "#", label: "Outworkers" },
      { to: "#", label: "Posts" },
      { to: "#", label: "Reports" },
      { to: "#", label: "Ready for Publications" },
      { to: "#", label: "Published Books" },
      { to: "#", label: "Olympia Websites Control Panel" },
    ],
  },
];
