export const books = [
  {
    sr: 1,
    title: "Gerald Dickens: My Life on the Road With A Christmas Carol",
    penName: "Gerald Dickens",
    imprint: "Olympia Publishers",
    datePublished: "30-11-2023",
    copiesSold: 250,
  },
  {
    sr: 2,
    title: "Dickens and Staplehurst: A Biography of a Rail Crash",
    penName: "Gerald Dickens",
    imprint: "Olympia Publishers",
    datePublished: "28-10-2021",
    copiesSold: 200,
  },
  {
    sr: 3,
    title: "Goodnight Zimbleville",
    penName: "Ryan Dewar",
    imprint: "Bumblebee Books",
    datePublished: "27-06-2024",
    copiesSold: 75,
  },
  {
    sr: 4,
    title: "Without Favour or Affection, Malice or Ill-Will",
    penName: "Steve Johnson",
    imprint: "Olympia Publishers",
    datePublished: "30-05-2024",
    copiesSold: 61,
  },
  {
    sr: 5,
    title: "Don't Stop Retrievin'",
    penName: "Raymond H Mayberry",
    imprint: "Bumblebee Books",
    datePublished: "28-10-2021",
    copiesSold: 50,
  },
  {
    sr: 6,
    title: "Mrs. V and the Misplaced Planet",
    penName: "Sarah Villarreal",
    imprint: "Bumblebee Books",
    datePublished: "27-06-2024",
    copiesSold: 40,
  },
  {
    sr: 7,
    title: "Burdened Hearts By Jesus’ Wounds, You are Healed",
    penName: "Elizabeth Minikel",
    imprint: "Olympia Publishers",
    datePublished: "27-06-2024",
    copiesSold: 40,
  },
  {
    sr: 8,
    title: "Sanctum Book One: Pestilent World",
    penName: "B K Moe",
    imprint: "Olympia Publishers",
    datePublished: "24-06-2021",
    copiesSold: 25,
  },
  {
    sr: 9,
    title: "The Potter",
    penName: "David Stanley",
    imprint: "Olympia Publishers",
    datePublished: "25-07-2024",
    copiesSold: 25,
  },
  {
    sr: 10,
    title: "My Adventure Journal",
    penName: "Dr Jocelyn Fleming",
    imprint: "Bumblebee Books",
    datePublished: "29-06-2023",
    copiesSold: 25,
  },
  {
    sr: 11,
    title: "A Variety of Veterinary Adventures",
    penName: "James Cameron Weir",
    imprint: "Olympia Publishers",
    datePublished: "25-02-2021",
    copiesSold: 22,
  },
  {
    sr: 12,
    title: "Di-Ablo's Revenge",
    penName: "Trevor Few",
    imprint: "Olympia Publishers",
    datePublished: "27-07-2023",
    copiesSold: 20,
  },
  {
    sr: 13,
    title: "The Remains of Stephanie Gayle",
    penName: "Michael James",
    imprint: "Olympia Publishers",
    datePublished: "29-02-2024",
    copiesSold: 20,
  },
  {
    sr: 14,
    title: "The Beast in the Bin",
    penName: "Michelle Boholst",
    imprint: "Bumblebee Books",
    datePublished: "27-06-2024",
    copiesSold: 16,
  },
  {
    sr: 15,
    title: "Bites of Cricket",
    penName: "Nick Cowley",
    imprint: "Olympia Publishers",
    datePublished: "29-02-2024",
    copiesSold: 15,
  },
  {
    sr: 16,
    title: "Cautionary Tales for Serious Seekers of Truth",
    penName: "Charley Lane",
    imprint: "Olympia Publishers",
    datePublished: "27-06-2024",
    copiesSold: 12,
  },
  {
    sr: 17,
    title: "The Tiger Who Ate Too Much Cheese",
    penName: "Timothy Robinson",
    imprint: "Bumblebee Books",
    datePublished: "26-10-2023",
    copiesSold: 10,
  },
  {
    sr: 18,
    title: "Danny And The Forbidden Devils",
    penName: "Zach Smith",
    imprint: "Olympia Publishers",
    datePublished: "30-07-2020",
    copiesSold: 10,
  },
  {
    sr: 19,
    title: "Tooth & Claw",
    penName: "Terry Mitchum",
    imprint: "Olympia Publishers",
    datePublished: "23-02-2023",
    copiesSold: 10,
  },
  {
    sr: 20,
    title: "The Little Monster",
    penName: "Marshall Johnston",
    imprint: "Bumblebee Books",
    datePublished: "31-03-2022",
    copiesSold: 10,
  },
];

export const olympiaBooks = [
  {
    sr: 1,
    title: "Gerald Dickens: My Life on the Road With A Christmas Carol",
    penName: "Gerald Dickens",
    imprint: "Olympia Publishers",
    datePublished: "30-11-2023",
    copiesSold: 250,
  },
  {
    sr: 2,
    title: "Dickens and Staplehurst: A Biography of a Rail Crash",
    penName: "Gerald Dickens",
    imprint: "Olympia Publishers",
    datePublished: "28-10-2021",
    copiesSold: 200,
  },
  {
    sr: 3,
    title: "Goodnight Zimbleville",
    penName: "Ryan Dewar",
    imprint: "Bumblebee Books",
    datePublished: "27-06-2024",
    copiesSold: 75,
  },
];
