export const data = [
  {
    company: "Waterstone's",
    title: "Mr.",
    firstName: "John",
    lastName: "Doe",
    designation: "The Manager",
    address1: "University of Essex",
    address2: "Main Building",
    address3: "Wivenhoe Park",
    townCity: "Colchester",
    stateCounty: "Essex",
    postCode: "CO4 3SQ",
    country: "England",
    telephone1: "01206 864773",
    telephone2: "01206 864774",
    email: "johndoe@waterstones.com",
    webAddress: "https://www.waterstones.com",
  },
  {
    company: "Waterstone's",
    title: "Ms.",
    firstName: "Jane",
    lastName: "Smith",
    designation: "The Manager",
    address1: "49-55 High Street",
    address2: "Suite 3",
    address3: "",
    townCity: "Southend-on-Sea",
    stateCounty: "Essex",
    postCode: "SS1 1HZ",
    country: "England",
    telephone1: "01702 437480",
    telephone2: "01702 437481",
    email: "janesmith@waterstones.com",
    webAddress: "https://www.waterstones.com",
  },
  {
    company: "Harts Bookshop",
    title: "Dr.",
    firstName: "Michael",
    lastName: "Brown",
    designation: "The Manager",
    address1: "5 King Street",
    address2: "Unit 2",
    address3: "",
    townCity: "Saffron Walden",
    stateCounty: "Essex",
    postCode: "CB10 1HT",
    country: "England",
    telephone1: "01799 508150",
    telephone2: "01799 508151",
    email: "michaelbrown@hartsbookshop.com",
    webAddress: "https://www.hartsbookshop.com",
  },
];
