export const AllContracts = [
    {
        status: "Under Production",
        penName: "Marcus Mmaribhekha",
        bookTitle: "The Future",
        imprint: "Olympia Publishers",
        contractDate: "05-08-2024",
        contractAmount: "£ 2100.00",
        authorForms: { form1: true, form2: false, form3: true },
        contractPaymentStatus: "Pending"
    },
    {
        status: "Under Production",
        penName: "Orfan Alam",
        bookTitle: "Alam",
        imprint: "Olympia Publishers",
        contractDate: "21-06-2024",
        contractAmount: "£ 3500.00",
        authorForms: { form1: false, form2: true, form3: true },
        contractPaymentStatus: "Traditional"
    },
    {
        status: "Under Production",
        penName: "T. M. Barber",
        bookTitle: "A Winter of Change",
        imprint: "Olympia Publishers",
        contractDate: "12-06-2024",
        contractAmount: "£ 2300.00",
        authorForms: { form1: true, form2: true, form3: false },
        contractPaymentStatus: "Paying"
    },
    {
        status: "Under Production",
        penName: "Rebecca Lawson",
        bookTitle: "Defending the Soul: Winning the Battle Against Spiritual Attack",
        imprint: "Olympia Publishers",
        contractDate: "23-05-2024",
        contractAmount: "£ 2500.00",
        authorForms: { form1: true, form2: false, form3: false },
        contractPaymentStatus: "Paid in Full"
    },
    {
        status: "Under Production",
        penName: "Aaron Noel",
        bookTitle: "My World Your Way",
        imprint: "Olympia Publishers",
        contractDate: "13-05-2024",
        contractAmount: "£ 2200.00",
        authorForms: { form1: false, form2: true, form3: false },
        contractPaymentStatus: "Hardback"
    },
    {
        status: "Under Production",
        penName: "Marcus Mmaribhekha",
        bookTitle: "The Future",
        imprint: "Olympia Publishers",
        contractDate: "05-08-2024",
        contractAmount: "£ 2100.00",
        authorForms: { form1: true, form2: false, form3: true },
        contractPaymentStatus: "Pending"
    },
    {
        status: "Under Production",
        penName: "Orfan Alam",
        bookTitle: "Alam",
        imprint: "Olympia Publishers",
        contractDate: "21-06-2024",
        contractAmount: "£ 3500.00",
        authorForms: { form1: false, form2: true, form3: true },
        contractPaymentStatus: "Traditional"
    },
    {
        status: "Under Production",
        penName: "T. M. Barber",
        bookTitle: "A Winter of Change",
        imprint: "Olympia Publishers",
        contractDate: "12-06-2024",
        contractAmount: "£ 2300.00",
        authorForms: { form1: true, form2: true, form3: false },
        contractPaymentStatus: "Paying"
    },
    {
        status: "Under Production",
        penName: "Rebecca Lawson",
        bookTitle: "Defending the Soul: Winning the Battle Against Spiritual Attack",
        imprint: "Olympia Publishers",
        contractDate: "23-05-2024",
        contractAmount: "£ 2500.00",
        authorForms: { form1: true, form2: false, form3: false },
        contractPaymentStatus: "Paid in Full"
    },
    {
        status: "Under Production",
        penName: "Aaron Noel",
        bookTitle: "My World Your Way",
        imprint: "Olympia Publishers",
        contractDate: "13-05-2024",
        contractAmount: "£ 2200.00",
        authorForms: { form1: false, form2: true, form3: false },
        contractPaymentStatus: "Hardback"
    },
    {
        status: "Under Production",
        penName: "Marcus Mmaribhekha",
        bookTitle: "The Future",
        imprint: "Olympia Publishers",
        contractDate: "05-08-2024",
        contractAmount: "£ 2100.00",
        authorForms: { form1: true, form2: false, form3: true },
        contractPaymentStatus: "Pending"
    },
    {
        status: "Under Production",
        penName: "Orfan Alam",
        bookTitle: "Alam",
        imprint: "Olympia Publishers",
        contractDate: "21-06-2024",
        contractAmount: "£ 3500.00",
        authorForms: { form1: false, form2: true, form3: true },
        contractPaymentStatus: "Traditional"
    },
    {
        status: "Under Production",
        penName: "T. M. Barber",
        bookTitle: "A Winter of Change",
        imprint: "Olympia Publishers",
        contractDate: "12-06-2024",
        contractAmount: "£ 2300.00",
        authorForms: { form1: true, form2: true, form3: false },
        contractPaymentStatus: "Paying"
    },
    {
        status: "Under Production",
        penName: "Rebecca Lawson",
        bookTitle: "Defending the Soul: Winning the Battle Against Spiritual Attack",
        imprint: "Olympia Publishers",
        contractDate: "23-05-2024",
        contractAmount: "£ 2500.00",
        authorForms: { form1: true, form2: false, form3: false },
        contractPaymentStatus: "Paid in Full"
    },
    {
        status: "Under Production",
        penName: "Aaron Noel",
        bookTitle: "My World Your Way",
        imprint: "Olympia Publishers",
        contractDate: "13-05-2024",
        contractAmount: "£ 2200.00",
        authorForms: { form1: false, form2: true, form3: false },
        contractPaymentStatus: "Hardback"
    }
];

export const invoicesData = [
    {
        status: "Under Production",
        imprint: "Olympia Publishers",
        contractDate: "01-08-2024",
        pubDate: "--",
        remDate: "--",
        authorName: "Mr. Aryeh Schwartz",
        penName: "Ari Kreischer",
        bookTitle: "School Daze",
        bookNo: 0,
        amount: 2200.00,
        vat: 0.00,
        total: 2200.00,
        paid: 0.00,
        paidByInvoice: 2200.00,
        remaining: 0.00,
        advanceAmount: 0.00,
        advancePaid: 0.00
    },
    {
        status: "Under Production",
        imprint: "Olympia Publishers",
        contractDate: "01-08-2024",
        pubDate: "--",
        remDate: "--",
        authorName: "Mr. Nigel Cook",
        penName: "Nigel Cook",
        bookTitle: "The Catalyst",
        bookNo: 6,
        amount: 3100.00,
        vat: 0.00,
        total: 3100.00,
        paid: 0.00,
        paidByInvoice: 3100.00,
        remaining: 0.00,
        advanceAmount: 0.00,
        advancePaid: 0.00
    },
    {
        status: "Under Production",
        imprint: "Olympia Publishers",
        contractDate: "01-08-2024",
        pubDate: "--",
        remDate: "--",
        authorName: "Ms. Lesley Cockburn",
        penName: "Elle Seaburn",
        bookTitle: "D.N.A.",
        bookNo: 1,
        amount: 2300.00,
        vat: 0.00,
        total: 2300.00,
        paid: 0.00,
        paidByInvoice: 2300.00,
        remaining: 0.00,
        advanceAmount: 0.00,
        advancePaid: 0.00
    },
    {
        status: "Under Production",
        imprint: "Olympia Publishers",
        contractDate: "01-08-2024",
        pubDate: "--",
        remDate: "--",
        authorName: "Dr. Kathy Martone",
        penName: "Kathy Martone",
        bookTitle: "Victorian Songlight: The Birthings of Magic & Mystery",
        bookNo: 1,
        amount: 2400.00,
        vat: 0.00,
        total: 2400.00,
        paid: 0.00,
        paidByInvoice: 240.00,
        remaining: 2160.00,
        advanceAmount: 0.00,
        advancePaid: 0.00
    },
    {
        status: "Under Production",
        imprint: "Bumblebee Books",
        contractDate: "02-08-2024",
        pubDate: "--",
        remDate: "--",
        authorName: "Mrs. Nic Girvan",
        penName: "Nic Girvan",
        bookTitle: "Nessie’s a Myth",
        bookNo: 1,
        amount: 2200.00,
        vat: 0.00,
        total: 2200.00,
        paid: 0.00,
        paidByInvoice: 2200.00,
        remaining: 0.00,
        advanceAmount: 0.00,
        advancePaid: 0.00
    },
    {
        status: "Under Production",
        imprint: "Olympia Publishers",
        contractDate: "02-08-2024",
        pubDate: "--",
        remDate: "--",
        authorName: "Mr. Nicholas Chilvers",
        penName: "Nicholas Chilvers",
        bookTitle: "On the Bench",
        bookNo: 1,
        amount: 2300.00,
        vat: 0.00,
        total: 2300.00,
        paid: 0.00,
        paidByInvoice: 2300.00,
        remaining: 0.00,
        advanceAmount: 0.00,
        advancePaid: 0.00
    },
    {
        status: "Under Production",
        imprint: "Olympia Publishers",
        contractDate: "02-08-2024",
        pubDate: "--",
        remDate: "--",
        authorName: "Mrs. Elena Boekestijn",
        penName: "Elena Vantroy",
        bookTitle: "October Snow",
        bookNo: 1,
        amount: 2800.00,
        vat: 0.00,
        total: 2800.00,
        paid: 0.00,
        paidByInvoice: 2800.00,
        remaining: 0.00,
        advanceAmount: 0.00,
        advancePaid: 0.00
    },
    {
        status: "Under Production",
        imprint: "Olympia Publishers",
        contractDate: "03-08-2024",
        pubDate: "--",
        remDate: "--",
        authorName: "Mrs. Alyssa Williams",
        penName: "Alyssa Desiree",
        bookTitle: "The Helen Montgomery Story: A Tale of Love, Temptation and Devotion",
        bookNo: 1,
        amount: 2200.00,
        vat: 0.00,
        total: 2200.00,
        paid: 0.00,
        paidByInvoice: 2200.00,
        remaining: 0.00,
        advanceAmount: 0.00,
        advancePaid: 0.00
    }
];

export const data = [
    {
        invoiceNo: 'INV001',
        client: 'Client A',
        date: '2024-08-01',
        amount: '$1000',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV002',
        client: 'Client B',
        date: '2024-08-02',
        amount: '$2000',
        status: 'Pending',
    },
    {
        invoiceNo: 'INV003',
        client: 'Client C',
        date: '2024-08-03',
        amount: '$1500',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV004',
        client: 'Client D',
        date: '2024-08-04',
        amount: '$500',
        status: 'Overdue',
    },
    {
        invoiceNo: 'INV005',
        client: 'Client E',
        date: '2024-08-05',
        amount: '$750',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV001',
        client: 'Client A',
        date: '2024-08-01',
        amount: '$1000',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV002',
        client: 'Client B',
        date: '2024-08-02',
        amount: '$2000',
        status: 'Pending',
    },
    {
        invoiceNo: 'INV003',
        client: 'Client C',
        date: '2024-08-03',
        amount: '$1500',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV004',
        client: 'Client D',
        date: '2024-08-04',
        amount: '$500',
        status: 'Overdue',
    },
    {
        invoiceNo: 'INV005',
        client: 'Client E',
        date: '2024-08-05',
        amount: '$750',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV001',
        client: 'Client A',
        date: '2024-08-01',
        amount: '$1000',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV002',
        client: 'Client B',
        date: '2024-08-02',
        amount: '$2000',
        status: 'Pending',
    },
    {
        invoiceNo: 'INV003',
        client: 'Client C',
        date: '2024-08-03',
        amount: '$1500',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV004',
        client: 'Client D',
        date: '2024-08-04',
        amount: '$500',
        status: 'Overdue',
    },
    {
        invoiceNo: 'INV005',
        client: 'Client E',
        date: '2024-08-05',
        amount: '$750',
        status: 'Paid',
    },

    {
        invoiceNo: 'INV001',
        client: 'Client A',
        date: '2024-08-01',
        amount: '$1000',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV002',
        client: 'Client B',
        date: '2024-08-02',
        amount: '$2000',
        status: 'Pending',
    },
    {
        invoiceNo: 'INV003',
        client: 'Client C',
        date: '2024-08-03',
        amount: '$1500',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV004',
        client: 'Client D',
        date: '2024-08-04',
        amount: '$500',
        status: 'Overdue',
    },
    {
        invoiceNo: 'INV005',
        client: 'Client E',
        date: '2024-08-05',
        amount: '$750',
        status: 'Paid',
    },
];

export const xerodata = [
    {
        invoiceNo: 'INV001',
        client: 'Client A',
        date: '2024-08-01',
        amount: '$1000',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV002',
        client: 'Client B',
        date: '2024-08-02',
        amount: '$2000',
        status: 'Pending',
    },
    {
        invoiceNo: 'INV003',
        client: 'Client C',
        date: '2024-08-03',
        amount: '$1500',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV004',
        client: 'Client D',
        date: '2024-08-04',
        amount: '$500',
        status: 'Overdue',
    },
    {
        invoiceNo: 'INV005',
        client: 'Client E',
        date: '2024-08-05',
        amount: '$750',
        status: 'Paid',
    },
];

export const pendingdata = [
    {
        invoiceNo: 'INV001',
        client: 'Client A',
        date: '2024-08-01',
        amount: '$1000',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV002',
        client: 'Client B',
        date: '2024-08-02',
        amount: '$2000',
        status: 'Pending',
    },
    {
        invoiceNo: 'INV003',
        client: 'Client C',
        date: '2024-08-03',
        amount: '$1500',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV004',
        client: 'Client D',
        date: '2024-08-04',
        amount: '$500',
        status: 'Overdue',
    },
    {
        invoiceNo: 'INV005',
        client: 'Client E',
        date: '2024-08-05',
        amount: '$750',
        status: 'Paid',
    },
];

export const paiddata = [
    {
        invoiceNo: 'INV001',
        client: 'Client A',
        date: '2024-08-01',
        amount: '$1000',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV002',
        client: 'Client B',
        date: '2024-08-02',
        amount: '$2000',
        status: 'Pending',
    },
    {
        invoiceNo: 'INV003',
        client: 'Client C',
        date: '2024-08-03',
        amount: '$1500',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV004',
        client: 'Client D',
        date: '2024-08-04',
        amount: '$500',
        status: 'Overdue',
    },
    {
        invoiceNo: 'INV005',
        client: 'Client E',
        date: '2024-08-05',
        amount: '$750',
        status: 'Paid',
    },
];

export const unpaiddata = [
    {
        invoiceNo: 'INV001',
        client: 'Client A',
        date: '2024-08-01',
        amount: '$1000',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV002',
        client: 'Client B',
        date: '2024-08-02',
        amount: '$2000',
        status: 'Pending',
    },
    {
        invoiceNo: 'INV003',
        client: 'Client C',
        date: '2024-08-03',
        amount: '$1500',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV004',
        client: 'Client D',
        date: '2024-08-04',
        amount: '$500',
        status: 'Overdue',
    },
    {
        invoiceNo: 'INV005',
        client: 'Client E',
        date: '2024-08-05',
        amount: '$750',
        status: 'Paid',
    },
];

export const overduedata = [
    {
        invoiceNo: 'INV001',
        client: 'Client A',
        date: '2024-08-01',
        amount: '$1000',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV002',
        client: 'Client B',
        date: '2024-08-02',
        amount: '$2000',
        status: 'Pending',
    },
    {
        invoiceNo: 'INV003',
        client: 'Client C',
        date: '2024-08-03',
        amount: '$1500',
        status: 'Paid',
    },
    {
        invoiceNo: 'INV004',
        client: 'Client D',
        date: '2024-08-04',
        amount: '$500',
        status: 'Overdue',
    },
    {
        invoiceNo: 'INV005',
        client: 'Client E',
        date: '2024-08-05',
        amount: '$750',
        status: 'Paid',
    },
];
