export const data = [
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Paid in Full",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Traditional",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Paid in Full",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Traditional",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Paid in Full",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Traditional",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
  {
    status: "Under Production",
    penName: "Edgardo Samaniego",
    bookTitle: "The True Adam and Eve in the Garden of Eden",
    imprint: "Olympia Publishers",
    isbn: "978-1-83543-485-7",
    readyForPublicationDate: "01-07-2024",
    contractDate: "05-09-2023",
    publicationDate: "dd-mm-yyyy",
    authorForms: { form1: true, form2: false, form3: true },
    paymentStatus: "Pending",
  },
];
