export const inputFields = [
    { label: "Author Name:", placeholder: "Author Name", value: "Mr. Martin Bulger" },
    { label: "Book Title:", placeholder: "Book Title", value: "Living Makes You Run Longer" },
    { label: "Pen Name:", placeholder: "Pen Name", value: "Martin Bulger" },
    { label: "Publication Date:", placeholder: "Publication Date", value: "04-07-2008" },
    { label: "ISBN:", placeholder: "ISBN", value: "978-1-90-551315-2" },
    { label: "Remainder Date:", placeholder: "Remainder Date", value: "13-08-2010" },
    { label: "Imprint:", placeholder: "Imprint", value: "Ebooks" },
    { label: "Contract Date:", placeholder: "Contract Date", value: "27-09-2007" },
    { label: "Book No:", placeholder: "Book No", value: "1" },
    { label: "Size:", placeholder: "Size", value: "234X156MM (Royal Portal)" },
    { label: "Format:", placeholder: "Format", value: "PAPERBACK EDITION" },
    { label: "Status:", placeholder: "Status", value: "Remaindered" },
];

export const lastTable = [
    {
        invoiceNo: "1704",
        invoiceDate: "27-01-2010",
        cnNo: "1704",
        cnDate: "--",
        client: "Amazon.co.uk (oly)",
        quantity: 1,
        net: 3.20,
        vat: "",
        totalAmount: "£3.20",
        amountPaid: 3.20,
        datePaid: "2010-02-26",
        hfSale: "homesale",
        royalty: "20%",
        saleType: "Amazon.co.uk",
        royalties: "Yes",
        royaltyAmount: "£ 0.64"
    },
    {
        invoiceNo: "1802",
        invoiceDate: "08-02-2010",
        cnNo: "--",
        cnDate: "--",
        client: "Amazon.co.uk (oly)",
        quantity: 1,
        net: 3.20,
        vat: "",
        totalAmount: "£3.20",
        amountPaid: 3.20,
        datePaid: "2010-03-30",
        hfSale: "homesale",
        royalty: "20%",
        saleType: "Amazon.co.uk",
        royalties: "Yes",
        royaltyAmount: "£ 0.64"
    },
    {
        invoiceNo: "1861",
        invoiceDate: "10-03-2010",
        cnNo: "--",
        cnDate: "--",
        client: "Amazon.co.uk (oly)",
        quantity: 1,
        net: 3.20,
        vat: "",
        totalAmount: "£3.20",
        amountPaid: 3.20,
        datePaid: "2010-07-18",
        hfSale: "homesale",
        royalty: "20%",
        saleType: "Amazon.co.uk",
        royalties: "Yes",
        royaltyAmount: "£ 0.64"
    },
    {
        invoiceNo: "1928",
        invoiceDate: "13-04-2010",
        cnNo: "--",
        cnDate: "--",
        client: "Amazon.co.uk (oly)",
        quantity: 1,
        net: 3.20,
        vat: "",
        totalAmount: "£3.20",
        amountPaid: 3.20,
        datePaid: "2010-07-18",
        hfSale: "homesale",
        royalty: "20%",
        saleType: "Amazon.co.uk",
        royalties: "Yes",
        royaltyAmount: "£ 0.64"
    }
];
