export const data = [
  {
    "Invoice Type": "Contract Invoice",
    Date: "14-05-2121",
    "Invoice number/Ref": "no number",
    "Contact name": "Rebecca Clark",
    "Card type": "Visa Debit",
    "Total amount": "£190",
    "Billing name": "",
    "Completed by": "Courtney",
    Status: "Processing",
    Manage: "view | Edit | Delete",
  },
  {
    "Invoice Type": "Contract Invoice",
    Date: "19-04-2121",
    "Invoice number/Ref": "no number",
    "Contact name": "Jennifer motley",
    "Card type": "Visa Debit",
    "Total amount": "£25",
    "Billing name": "",
    "Completed by": "Courtney",
    Status: "Processing",
    Manage: "view | Edit | Delete",
  },
  {
    "Invoice Type": "Contract Invoice",
    Date: "14-05-2121",
    "Invoice number/Ref": "no number",
    "Contact name": "Rebecca Clark",
    "Card type": "Visa Debit",
    "Total amount": "£190",
    "Billing name": "",
    "Completed by": "Courtney",
    Status: "Processing",
    Manage: "view | Edit | Delete",
  },
  {
    "Invoice Type": "Contract Invoice",
    Date: "19-04-2121",
    "Invoice number/Ref": "no number",
    "Contact name": "Jennifer motley",
    "Card type": "Visa Debit",
    "Total amount": "£25",
    "Billing name": "",
    "Completed by": "Courtney",
    Status: "Processing",
    Manage: "view | Edit | Delete",
  },
  {
    "Invoice Type": "Contract Invoice",
    Date: "14-05-2121",
    "Invoice number/Ref": "no number",
    "Contact name": "Rebecca Clark",
    "Card type": "Visa Debit",
    "Total amount": "£190",
    "Billing name": "",
    "Completed by": "Courtney",
    Status: "Processing",
    Manage: "view | Edit | Delete",
  },
  {
    "Invoice Type": "Contract Invoice",
    Date: "19-04-2121",
    "Invoice number/Ref": "no number",
    "Contact name": "Jennifer motley",
    "Card type": "Visa Debit",
    "Total amount": "£25",
    "Billing name": "",
    "Completed by": "Courtney",
    Status: "Processing",
    Manage: "view | Edit | Delete",
  },
];
